# Generated by Django 6.0.4 on 2026-04-25 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(help_text='Format: XXXXX-XXXXXXX-X', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid CNIC in format XXXXX-XXXXXXX-X.', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number e.g. 03001234567.', regex='^\\+?92\\d{10}$|^0\\d{10}$')])),
                ('address', models.TextField()),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('JOINT', 'Joint'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['cnic'], name='unique_customer_cnic'), models.Index(fields=['full_name'], name='idx_customer_name')],
            },
        ),
    ]
