# Generated by Django 6.0.4 on 2026-05-05 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Format: 03001234567 or +923001234567', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number e.g. 03001234567.', regex='^\\+?92\\d{10}$|^0\\d{10}$')]),
        ),
    ]
