# Generated by Django 6.0.4 on 2026-05-06 07:40

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(db_index=True, help_text='Format: XXXXX-XXXXXXX-X', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid CNIC in format XXXXX-XXXXXXX-X.', regex='^\\d{5}-\\d{7}-\\d{1}$')])),
                ('phone', models.CharField(help_text='Format: 03001234567 or +923001234567', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani phone number e.g. 03001234567.', regex='^\\+?92\\d{10}$|^0\\d{10}$')])),
                ('address', models.TextField()),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('JOINT', 'Joint'), ('CORPORATE', 'Corporate')], default='INDIVIDUAL', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Customer',
                'verbose_name_plural': 'historical Customers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
