# Generated by Django 6.0.4 on 2026-05-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
