# Generated by Django 6.0.4 on 2026-04-24 07:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('total_area', models.PositiveIntegerField()),
                ('area_unit', models.CharField(choices=[('MARLA', 'Marla'), ('KANAL', 'Kanal'), ('SQFT', 'Square Feet')], default='MARLA', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=20)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('size_unit', models.CharField(choices=[('MARLA', 'Marla'), ('KANAL', 'Kanal'), ('SQFT', 'Square Feet')], default='MARLA', max_length=10)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial')], default='RESIDENTIAL', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='projects_and_plots.project')),
            ],
            options={
                'verbose_name': 'Plot',
                'verbose_name_plural': 'Plots',
                'ordering': ['project', 'block', 'plot_number'],
                'indexes': [models.Index(fields=['status'], name='idx_plot_status')],
                'constraints': [models.UniqueConstraint(fields=('project', 'plot_number'), name='unique_plot_per_project')],
            },
        ),
    ]
