# Generated by Django 6.0.4 on 2026-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('TOKEN', 'Token'), ('BOOKED', 'Booked'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=15),
        ),
    ]
