# Generated by Django 6.0.4 on 2026-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0002_alter_plot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_plots',
            field=models.PositiveIntegerField(default=0, help_text='Total number of plots in this project'),
        ),
    ]
