# Generated by Django 6.0.4 on 2026-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0003_project_total_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='RLD', help_text="Short project code, e.g., 'RBS' for Royal Bahria", max_length=10, unique=True),
        ),
    ]
