# Generated by Django 6.0.4 on 2026-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0004_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default='ROLD', help_text="Short project code, e.g., 'RBS' for Royal Bahria", max_length=10, unique=True),
        ),
    ]
