# Generated by Django 6.0.4 on 2026-05-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0005_alter_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
    ]
