# Generated by Django 6.0.4 on 2026-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0007_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Wide banner (recommended 800×200 px)', null=True, upload_to='projects/logos/'),
        ),
    ]
