# Generated by Django 6.0.4 on 2026-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_and_plots', '0008_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text='Full office/contact address printed on payment challans', max_length=200),
        ),
    ]
