# Generated by Django 6.0.4 on 2026-04-28 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('projects_and_plots', '0002_alter_plot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('plot',), name='unique_active_booking_per_plot'),
        ),
    ]
