# Generated by Django 6.0.4 on 2026-05-04 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_unique_active_booking_per_plot'),
        ('customers', '0001_initial'),
        ('projects_and_plots', '0007_project_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_plot',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('is_deleted', False)), fields=('plot',), name='unique_active_booking_per_plot'),
        ),
    ]
