# Generated by Django 6.0.4 on 2026-05-07 05:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_historicalbooking_historicalinstallment'),
        ('customers', '0003_historicalcustomer'),
        ('projects_and_plots', '0010_historicalplot_historicalproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('CNIC', 'CNIC Copy'), ('TOKEN_RECEIPT', 'Token Receipt'), ('SALE_AGREEMENT', 'Sale Agreement'), ('ALLOTMENT_LETTER', 'Allotment Letter'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('OTHER', 'Other')], help_text='Type of document being uploaded.', max_length=20)),
                ('file', models.FileField(help_text='PDF, image, or scanned document.', upload_to='bookings/documents/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Optional note about this document.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Document',
                'verbose_name_plural': 'Booking Documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_plot',
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment_received_on',
            field=models.DateField(blank=True, help_text='Date down payment was collected. Set this when payment is received — triggers status change to ACTIVE.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='token_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount received as token to hold the plot. Appears on the token challan. May be zero for direct bookings.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='token_received_on',
            field=models.DateField(blank=True, help_text='Date token payment was physically received.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='down_payment_received_on',
            field=models.DateField(blank=True, help_text='Date down payment was collected. Set this when payment is received — triggers status change to ACTIVE.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='token_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount received as token to hold the plot. Appears on the token challan. May be zero for direct bookings.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='token_received_on',
            field=models.DateField(blank=True, help_text='Date token payment was physically received.', null=True),
        ),
        migrations.AddField(
            model_name='historicalinstallment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstallment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinstallment',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date the booking was registered.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, help_text='Down payment amount (excluding token). Total upfront = token_amount + down_payment.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_plan',
            field=models.CharField(choices=[('LUMP', 'Lump Sum'), ('3YR', 'Three Year'), ('5YR', 'Five Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('TOKEN', 'Token'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TOKEN', help_text='TOKEN → token received, awaiting down payment. ACTIVE → down payment collected, installments running. COMPLETED → all payments received. CANCELLED → booking void.', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Agreed total sale price of the plot.', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date the booking was registered.'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, help_text='Down payment amount (excluding token). Total upfront = token_amount + down_payment.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='payment_plan',
            field=models.CharField(choices=[('LUMP', 'Lump Sum'), ('3YR', 'Three Year'), ('5YR', 'Five Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='status',
            field=models.CharField(choices=[('TOKEN', 'Token'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TOKEN', help_text='TOKEN → token received, awaiting down payment. ACTIVE → down payment collected, installments running. COMPLETED → all payments received. CANCELLED → booking void.', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Agreed total sale price of the plot.', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinstallment',
            name='challan_number',
            field=models.CharField(db_index=True, help_text='System-generated challan reference number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalinstallment',
            name='installment_number',
            field=models.PositiveIntegerField(help_text='Sequential number within this booking (1, 2, 3 …).'),
        ),
        migrations.AlterField(
            model_name='historicalinstallment',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Date payment was physically received.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalinstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='installment',
            name='challan_number',
            field=models.CharField(help_text='System-generated challan reference number.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(help_text='Sequential number within this booking (1, 2, 3 …).'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Date payment was physically received.', null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['TOKEN', 'ACTIVE']), ('is_deleted', False)), fields=('plot',), name='unique_active_booking_per_plot'),
        ),
        migrations.AddField(
            model_name='bookingdocument',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_booking_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
