# Generated by Django 6.0.4 on 2026-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_plan',
            field=models.CharField(choices=[('LUMP', 'Lump Sum'), ('6M', '6 Months'), ('1YR', 'One Year'), ('2YR', 'Two Year'), ('3YR', 'Three Year'), ('5YR', 'Five Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='payment_plan',
            field=models.CharField(choices=[('LUMP', 'Lump Sum'), ('6M', '6 Months'), ('1YR', 'One Year'), ('2YR', 'Two Year'), ('3YR', 'Three Year'), ('5YR', 'Five Year')], max_length=10),
        ),
    ]
