# Generated by Django 6.0.4 on 2026-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstallment',
            name='receipt',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Payment Receipt'),
        ),
        migrations.AddField(
            model_name='installment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='installments/receipts/%Y/%m/', verbose_name='Payment Receipt'),
        ),
    ]
