# Generated by Django 6.0.4 on 2026-05-05 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects_and_plots', '0007_project_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('construction', 'Construction'), ('marketing', 'Marketing'), ('salaries', 'Staff Salaries'), ('utilities', 'Utilities'), ('legal', 'Legal'), ('miscellaneous', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=10)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, help_text='Optional — receipt, invoice, or cheque scan', null=True, upload_to='expenses/documents/%Y/%m/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects_and_plots.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='idx_expense_project'), models.Index(fields=['category'], name='idx_expense_category'), models.Index(fields=['date'], name='idx_expense_date')],
            },
        ),
    ]
