# Generated by Django 6.0.4 on 2026-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_historicalexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('daily_labour', 'Daily Labour'), ('salaries', 'Staff Salaries'), ('transportation', 'Transportation & Fuel'), ('government_fees', 'Government Fees & NOC'), ('commission', 'Agent Commission'), ('marketing', 'Marketing & Advertising'), ('utilities', 'Utilities'), ('equipment_rental', 'Equipment Rental'), ('maintenance', 'Maintenance & Repair'), ('office_supplies', 'Office Supplies'), ('food', 'Food'), ('rent', 'Office / Site Rent'), ('security', 'Security'), ('legal', 'Legal & Documentation'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Duties'), ('miscellaneous', 'Miscellaneous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('daily_labour', 'Daily Labour'), ('salaries', 'Staff Salaries'), ('transportation', 'Transportation & Fuel'), ('government_fees', 'Government Fees & NOC'), ('commission', 'Agent Commission'), ('marketing', 'Marketing & Advertising'), ('utilities', 'Utilities'), ('equipment_rental', 'Equipment Rental'), ('maintenance', 'Maintenance & Repair'), ('office_supplies', 'Office Supplies'), ('food', 'Food'), ('rent', 'Office / Site Rent'), ('security', 'Security'), ('legal', 'Legal & Documentation'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Duties'), ('miscellaneous', 'Miscellaneous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online')], max_length=10),
        ),
    ]
